config/routes.rb
Rails.application.routes.draw do

  resources :hackdays do
    resources :hacks, :except => [:update] do
      collection do
        put 'submit_vote'
      end
    end
  end

  root to: "hackdays#index"

end

app/models/hack.rb
class Hack < ActiveRecord::Base
  belongs_to :hackday
  validates :title, presence: true
  validates :people,  presence: true
end

app/models/hackday.rb
class Hackday < ActiveRecord::Base
  has_many :hacks
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/hackdays_controller.rb
class HackdaysController < ApplicationController

  def index
    @hackdays = Hackday.all.reverse
  end

  def new
    @hackday = Hackday.new
  end

  def create
    @hackday = Hackday.new(hackday_params)
    if @hackday.save
      redirect_to hackdays_path
    else
      render 'new'
    end
  end

  def show
    @hackday = Hackday.find_by_id(params[:id])
    if @hackday
      return @hackday
    else
      render :status => 400
    end
  end

  private

  def hackday_params
    params.require(:hackday).permit(:name)
  end
end

app/controllers/hacks_controller.rb
class HacksController < ApplicationController
  before_filter :find_hackday, :set_votes

  def index
    @hacks = @hackday.hacks.all
  end
  
  def show
    @hack = @hackday.hacks.find_by_id(params[:id])
  end

  def new
    @hack = @hackday.hacks.new
  end

  def create
    @hack = @hackday.hacks.new(hack_params)
    if @hack.save
      redirect_to hackday_hacks_path
    else
      render 'new'
    end
  end

  def submit_vote
    @hack = Hack.find_by_id(params[:hack_id])
    if get_num_votes(@hackday) > 0
      decrease_votes(@hackday)
      @hack.class.update_counters @hack.id, :votes => 1
      @hack.save
      flash[:success] = "Thanks you for voting"
    else
      flash[:error] = "You have already voted 3 times"
    end
    redirect_to hackday_hacks_path(params[:hackday_id])
  end

  protected

  NUM_VOTES = 3

  def find_hackday
    @hackday = Hackday.find_by_id(params[:hackday_id])
  end

  def get_num_votes(hackday)
    return session[:hackday_id][:votes]
  end

  def decrease_votes(hackday)
    @votes = session[:hackday_id][:votes]
    @votes -=1
    session[:hackday_id][:votes] = @votes
  end

  private
  def hack_params
    params.require(:hack).permit(:title, :people)
  end

  def set_votes
    session[:hackday_id] = {:votes => NUM_VOTES}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dynamic_pages_helper.rb
module DynamicPagesHelper
end

app/helpers/hackdays_helper.rb
module HackdaysHelper
end

app/helpers/hacks_helper.rb
module HacksHelper
end

app/views/dynamic_pages/create.html.erb
<h1>Create New HackDay </h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@hack_day) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.hack :hack %>
      <%= f.text_field :hack %>

      <%= f.submit "Create HackDay", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/dynamic_pages/hackday.html.erb
<% provide(:title, 'Home') %>
<!DOCTYPE html>
<html>
  <head>
    <title>HackDay Voting | <%= yield(:title) %></title>
  </head>
  <body>
    <h1>HackDay List</h1>
    <%= radio_button_tag(:age, "child") %>
<%= label_tag(:age_child, "Test") %>
  <body>
</html>

app/views/dynamic_pages/home.html.erb
<% provide(:title, 'Home') %>
<!DOCTYPE html>
<html>
  <head>
    <title>HackDay Voting | <%= yield(:title) %></title>
  </head>
  <body>
    <h1>HackDay List</h1>
  <body>
</html>

app/views/hackdays/index.html.erb
<h1>HackDays</h1>
<div class="row">
  <div class= "span6 offset3">
    <% @hackdays.each do |hackday| %>
    <center>
      <p>
        <%= link_to hackday.name, hackday_hacks_path(hackday) %>
      </p>
    </center>
    <% end %>
  </div>
</div>

app/views/hackdays/new.html.erb
<h1>Create A New Hackday</h1>
<div class "row">
  <div class="span6 offset3">
    <center>
      <%= form_for(@hackday) do |f| %>

        <%= f.label :name %>
        <%= f.text_field :name %>
        
        <p>
          <%= f.submit "Create new hackday!", class: "btn btn-large btn-primary" %>
        </p>
      <% end %>
    </center>
  </div>
</div>

app/views/hackdays/show.html.erb
<h1><%= @hackday.name %></h1>

app/views/hacks/index.html.erb
<% provide(:title, @hackday.name) %>
<h1> <%=yield(:title) %> </h1>
<center>
  <%= link_to "Add a new Hack", new_hackday_hack_path, class: "btn btn-large btn-primary" %>
</center>
<div class="row">
  <%= form_tag(submit_vote_hackday_hacks_path, :method => "put") do %>
  <% @hacks.each do |hack| %>
    <p>
      <center>
        <%= radio_button_tag(:hack_id, hack.id) %>
        <%= label_tag(:voters, "#{hack.title} by #{hack.people} with #{hack.votes.to_s} votes") %>
      </center>
    </p>
  <% end %>
  <div>
    <center>
      <%= submit_tag "Vote", class: "btn btn-large btn-primary" %>
    </center>
  </div>
  <% end %>
</div>

app/views/hacks/new.html.erb
<h1>Add New Hack</h1>

<div class="row">
  <div class="span6 offset3">
    <center>
     <%= form_for [@hackday, @hack] do |f| %>
      <%= render 'shared/error_messages' %>

       <%= f.label :title %>
       <%= f.text_field :title %>

       <%= f.label :people %>
       <%= f.text_field :people %>
      
      <p>
        <%= f.submit "Create hack!", class: "btn btn-large btn-primary" %>
      </p>
     <% end %>
    </center>
  </div>
</div>

app/views/hacks/show.html.erb
<%= @hack.title %>, <%= @hack.people %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hackday Voting</title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "HackDay Voting", root_path, id: "logo" %>
          <nav>
            <ul class="nav pull-right">
              <li><%= link_to "Add HackDay",  new_hackday_path %></li>
            </ul>
          </nav>
        </div>
      </div>
    </header>
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @hack.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@hack.errors.count, "error") %>.
    </div>
    <ul>
    <% @hack.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>